#!/usr/bin/env bash

DEFAULT_NETWORK_BYTE='C'
CHECKED_NETWORK_BYTE=${WAVES_NETWORK_BYTE:-$DEFAULT_NETWORK_BYTE}

DEFAULT_NODE_API_URI='http://node0:6816'
CHECKED_NODE_API_URI=${WAVES_NODE_API_URI:-$DEFAULT_NODE_API_URI}

DEFAULT_BLOCKCHAIN_NAME='Devnet'
CHECKED_BLOCKCHAIN_NAME=${WAVES_BLOCKCHAIN_NAME:-$DEFAULT_BLOCKCHAIN_NAME}

DEFAULT_NODES_LIST=''
CHECKED_NODES_LIST=${WAVES_NODES_LIST:-$DEFAULT_NODES_LIST}


DEFAULT_DATA_SERVICES_PORT='3000'
CHECKED_DATA_SERVICES_PORT=${WAVES_DATA_SERVICES_PORT:-$DEFAULT_DATA_SERVICES_PORT}

DEFAULT_BLOCKCHAIN_HEIGHT=1000
CHECKED_BLOCKCHAIN_HEIGHT=${WAVES_BLOCKCHAIN_HEIGHT:-$DEFAULT_BLOCKCHAIN_HEIGHT}


cd /var/src
NETWORK_BYTE="$CHECKED_NETWORK_BYTE" NODE_API_URI="$CHECKED_NODE_API_URI" BLOCKCHAIN_NAME="$CHECKED_BLOCKCHAIN_NAME" NODES="$CHECKED_NODES_LIST" DATA_SERVICES_PORT="$CHECKED_DATA_SERVICES_PORT" python3 ./generateExplorerConfig.py

cd /var/src/WavesExplorerLite
sudo gulp distr --allow-root

sudo service postgresql start

cd /var/src/blockchain-postgres-sync
sudo NODE_API_URI="$CHECKED_NODE_API_URI" python3 /var/src/generateDataServiceConfig.py
sudo npm run download 0 $CHECKED_BLOCKCHAIN_HEIGHT
sudo pm2 start npm -- start updateComposite

cd /var/src/data-service
sudo export $(cat variables.env | xargs) && NODE_ENV=production node src/index.js
